fn main() {
    // tauri-build validates `bundle.resources` globs at compile time, but
    // bundle-dlls/ is generated by scripts/stage-dlls.mjs only at bundle time
    // (beforeBundleCommand). Seed an empty .keep so the `bundle-dlls/*` glob
    // matches on fresh checkouts (dev clones, CI debug builds) and plain
    // `cargo build`/`clippy` don't fail before bundling ever happens. The .keep
    // never ships: stage-dlls.mjs wipes and recreates the dir with the real
    // DLLs before the bundler collects resources.
    let dlls = std::path::Path::new("bundle-dlls");
    let _ = std::fs::create_dir_all(dlls);
    let is_empty = std::fs::read_dir(dlls)
        .map(|mut d| d.next().is_none())
        .unwrap_or(true);
    if is_empty {
        let _ = std::fs::write(dlls.join(".keep"), b"");
    }

    tauri_build::build()
}
